services:
  workspace:
    container_name: streamlit-sample-app-development
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      PYTHONPATH: /workspace
    volumes:
      - ..:/workspace
